# important token
AUTH_TOKEN = API_KEY = "370b0b6f-3f09-4807-b7fe-270a4e5ba2c2"

# scansan API
SEARCH_URL = "https://api.scansan.com/v1/area_codes/search"
SUMMARY_URL = """https://api.scansan.com/v1/area_codes/{area_code}/summary"""
SALE_HISTORY_URL = """https://api.scansan.com/v1/postcode/{area_code}/sale/history"""
CURRENT_VALUATIONS_URL = """https://api.scansan.com/v1/postcode/{area_code}/valuations/current"""
HISTORICAL_VALUATIONS_URL = """https://api.scansan.com/v1/postcode/{area_code}/valuations/historical"""

# header
HEADERS = {
"X-Auth-Token": AUTH_TOKEN, # for authentication
"Content-Type": "application/json" # indicates request is JSON
}

# UK areas
UK_AREAS = [
    "Aberdeen",
    "Anglesey",
    "Angus",
    "Bangor",
    "Barnet",
    "Bath",
    "Bedfordshire",
    "Belfast",
    "Berkshire",
    "Bexley",
    "Birmingham",
    "Blackburn",
    "Blackpool",
    "Blaenau Gwent",
    "Bolton",
    "Bournemouth",
    "Bracknell Forest",
    "Bradford",
    "Brent",
    "Bridgend",
    "Bristol",
    "Brixton",
    "Bromley",
    "Buckinghamshire",
    "Bury",
    "Caerphilly",
    "Cambridgeshire",
    "Cambridge",
    "Camden",
    "Cardiff",
    "Carmarthenshire",
    "Ceredigion",
    "Cheshire",
    "Chelmsford",
    "Cheltenham",
    "Chester",
    "Colchester",
    "Conwy",
    "Cornwall",
    "Coventry",
    "Croydon",
    "Cumbria",
    "Darlington",
    "Denbighshire",
    "Derby",
    "Derbyshire",
    "Derry",
    "Devon",
    "Doncaster",
    "Dorset",
    "Dudley",
    "Dundee",
    "Durham",
    "Ealing",
    "East Sussex",
    "Edinburgh",
    "Enfield",
    "England",
    "Essex",
    "Exeter",
    "Falkirk",
    "Flintshire",
    "Gateshead",
    "Glasgow",
    "Gloucester",
    "Gloucestershire",
    "Greenwich",
    "Gwynedd",
    "Hackney",
    "Halifax",
    "Hammersmith and Fulham",
    "Hampshire",
    "Haringey",
    "Harrow",
    "Hartlepool",
    "Havering",
    "Hereford",
    "Herefordshire",
    "Hertfordshire",
    "Highland",
    "Hillingdon",
    "Hounslow",
    "Hove",
    "Huddersfield",
    "Inverness",
    "Ipswich",
    "Islington",
    "Kensington and Chelsea",
    "Kent",
    "Kingston upon Thames",
    "Lambeth",
    "Lancashire",
    "Leeds",
    "Leicester",
    "Leicestershire",
    "Lewisham",
    "Lincolnshire",
    "Lisburn",
    "Liverpool",
    "London",
    "Luton",
    "Manchester",
    "Medway",
    "Merthyr Tydfil",
    "Midlothian",
    "Milton Keynes",
    "Monmouthshire",
    "Moray",
    "Merton",
    "Middlesbrough",
    "Neath Port Talbot",
    "Newcastle upon Tyne",
    "Newham",
    "Newport",
    "Newry",
    "Norfolk",
    "North Northamptonshire",
    "North Somerset",
    "North Tyneside",
    "North Yorkshire",
    "Northamptonshire",
    "Northumberland",
    "Nottingham",
    "Nottinghamshire",
    "Norwich",
    "Oldham",
    "Oxfordshire",
    "Pembrokeshire",
    "Perth",
    "Peterborough",
    "Plymouth",
    "Poole",
    "Portsmouth",
    "Powys",
    "Preston",
    "Reading",
    "Redbridge",
    "Rhondda Cynon Taf",
    "Richmond upon Thames",
    "Rochdale",
    "Rutland",
    "Salford",
    "Scarborough",
    "Scotland",
    "Sefton",
    "Sheffield",
    "Shropshire",
    "Slough",
    "Solihull",
    "Somerset",
    "South Gloucestershire",
    "South Tyneside",
    "Southampton",
    "Southend-on-Sea",
    "Southwark",
    "Staffordshire",
    "Stirling",
    "Stockport",
    "Stoke-on-Trent",
    "Suffolk",
    "Sunderland",
    "Surrey",
    "Sutton",
    "Swansea",
    "Swindon",
    "Telford",
    "Thurrock",
    "Torfaen",
    "Torquay",
    "Tower Hamlets",
    "Trafford",
    "Wakefield",
    "Wales",
    "Waltham Forest",
    "Wandsworth",
    "Warrington",
    "Warwickshire",
    "West Sussex",
    "Westminster",
    "Wigan",
    "Wiltshire",
    "Wokingham",
    "Wolverhampton",
    "Worcester",
    "Worcestershire",
    "Wrexham",
    "York",
]