UK_AREAS = [
    "Aberdeen",
    "Aberdeenshire",
    "Anglesey",
    "Angus",
    "Antrim and Newtownabbey",
    "Ards and North Down",
    "Argyll and Bute",
    "Armagh City, Banbridge and Craigavon",

    "Bangor",
    "Barnet",
    "Bath",
    "Bedfordshire",
    "Belfast",
    "Berkshire",
    "Bexley",
    "Birmingham",
    "Blackburn",
    "Blackpool",
    "Blaenau Gwent",
    "Bolton",
    "Bournemouth",
    "Bracknell Forest",
    "Bradford",
    "Brent",
    "Bridgend",
    "Bristol",
    "Bromley",
    "Buckinghamshire",
    "Bury",

    "Caerphilly",
    "Cambridgeshire",
    "Cambridge",
    "Camden",
    "Cardiff",
    "Carmarthenshire",
    "Causeway Coast and Glens",
    "Ceredigion",
    "Cheshire",
    "Chelmsford",
    "Cheltenham",
    "Chester",
    "Clackmannanshire",
    "Colchester",
    "Conwy",
    "Cornwall",
    "Coventry",
    "Croydon",
    "Cumbria",

    "Darlington",
    "Denbighshire",
    "Derby",
    "Derbyshire",
    "Derry",
    "Devon",
    "Doncaster",
    "Dorset",
    "Dudley",
    "Dumfries and Galloway",
    "Dundee",
    "Durham",

    "Ealing",
    "East Ayrshire",
    "East Dunbartonshire",
    "East Lothian",
    "East Midlands",
    "East of England",
    "East Renfrewshire",
    "East Sussex",
    "Edinburgh",
    "Enfield",
    "England",
    "Essex",
    "Exeter",
    "Falkirk",
    "Fermanagh and Omagh",
    "Fife",
    "Flintshire",

    "Gateshead",
    "Glasgow",
    "Gloucester",
    "Gloucestershire",
    "Greater London",
    "Greater Manchester",
    "Greenwich",
    "Gwynedd",

    "Hackney",
    "Halifax",
    "Hammersmith and Fulham",
    "Hampshire",
    "Haringey",
    "Harrow",
    "Hartlepool",
    "Havering",
    "Hereford",
    "Herefordshire",
    "Hertfordshire",
    "Highland",
    "Hillingdon",
    "Hounslow",
    "Hove",
    "Huddersfield",

    "Inverness",
    "Ipswich",
    "Isle of Wight",
    "Islington",

    "Kensington and Chelsea",
    "Kent",
    "Kingston upon Thames",

    "Lambeth",
    "Lancashire",
    "Leeds",
    "Leicester",
    "Leicestershire",
    "Lewisham",
    "Lincolnshire",
    "Lisburn",
    "Liverpool",
    "London",
    "Luton",

    "Manchester",
    "Medway",
    "Merseyside",
    "Merthyr Tydfil",
    "Midlothian",
    "Milton Keynes",
    "Monmouthshire",
    "Moray",
    "Merton",
    "Middlesbrough",

    "Na h-Eileanan Siar",
    "Neath Port Talbot",
    "Newcastle upon Tyne",
    "Newham",
    "Newport",
    "Newry",
    "Norfolk",
    "North Ayrshire",
    "North East England",
    "North Lanarkshire",
    "North Northamptonshire",
    "North Somerset",
    "North Tyneside",
    "North West England",
    "North Yorkshire",
    "Northamptonshire",
    "Northumberland",
    "Northern Ireland",
    "Nottingham",
    "Nottinghamshire",
    "Norwich",

    "Oldham",
    "Orkney Islands",
    "Oxfordshire",

    "Pembrokeshire",
    "Perth",
    "Peterborough",
    "Plymouth",
    "Poole",
    "Portsmouth",
    "Powys",
    "Preston",

    "Reading",
    "Redbridge",
    "Renfrewshire",
    "Rhondda Cynon Taf",
    "Richmond upon Thames",
    "Rochdale",
    "Rutland",

    "Salford",
    "Scarborough",
    "Scotland",
    "Scottish Borders",
    "Sefton",
    "Sheffield",
    "Shetland Islands",
    "Shropshire",
    "Slough",
    "Solihull",
    "Somerset",
    "South Ayrshire",
    "South East England",
    "South Gloucestershire",
    "South Lanarkshire",
    "South Shields",
    "South Tyneside",
    "South West England",
    "Southampton",
    "Southend-on-Sea",
    "Southwark",
    "St Helens",
    "Staffordshire",
    "Stirling",
    "Stockport",
    "Stoke-on-Trent",
    "Suffolk",
    "Sunderland",
    "Surrey",
    "Sutton",
    "Swansea",
    "Swindon",

    "Telford",
    "Thurrock",
    "Torfaen",
    "Torquay",
    "Tower Hamlets",
    "Trafford",
    "Tyne and Wear",

    "Vale of Glamorgan",
    "Wakefield",
    "Wales",
    "Waltham Forest",
    "Wandsworth",
    "Warrington",
    "Warwickshire",
    "West Dunbartonshire",
    "West Lothian",
    "West Midlands",
    "West Sussex",
    "Westminster",
    "Wigan",
    "Wiltshire",
    "Wokingham",
    "Wolverhampton",
    "Worcester",
    "Worcestershire",
    "Wrexham",

    "York",
    "Yorkshire and the Humber",
]